In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3],[4,5,6]])

print(b.shape)#Dimensions of the array
print(b.ndim)#Number of dimensions
print(a.dtype)#Data type of the array

c=np.zeros((2,3))#Array of zeros with shape (2,3)
d=np.ones((3,4))#Array of ones with shape (3,4)
c=np.arange(0,10,1)#Array of even numbers from 0 to 10  np.arange(start, stop, step)
e=np.linspace(0,1,5)#it divides the interval [0,1] into 5 equal parts and returns the endpoints of those parts 

print(c)
print(d)
print(e)

(2, 3)
2
int64
[0 1 2 3 4 5 6 7 8 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.   0.25 0.5  0.75 1.  ]
