In [3]:
import numpy as np
import time
import sys
SIZE=1000
l1=range(SIZE)
l2=range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)
start=time.time()
result=[(x,y) for x,y in zip(l1,l2)]
print("Time taken for list comprehension: ",(time.time()-start)*1000)
start=time.time()
result=a1+a2
print("Time taken for numpy array addition: ",(time.time()-start)*1000)

Time taken for list comprehension:  0.0
Time taken for numpy array addition:  1.0194778442382812


In [9]:
import numpy as np
import time
start=time.time()
r=[]
l=list(range(1000000))

for i in l:
    r.append(i**2)
    e=time.time()
    
print("Time taken for list comprehension: ",(e-start))

Time taken for list comprehension:  0.2733900547027588


In [ ]:
a=np.arange(1000000)
start=time.time()
result=a**2
print("List time ",(time.time()-start))

List time  0.003996372222900391


In [25]:
a=np.arange(1000000)
start=time.time()
result=a**2
e=time.time()
print("List time ",(e-start))

List time  0.00549769401550293


In [3]:
import numpy as np
d=np.full((3,3),6,dtype='complex')
print("\nAn array is initialized with all 6s of complex type:",d)
e=np.random.rand(2,2)
print("\nA 2x2 array of random numbers",e)
f=np.arange(0,30,5)
print("\nAn array with values from 0 to 30 with a step of 5:",f)


An array is initialized with all 6s of complex type: [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A 2x2 array of random numbers [[0.43458142 0.94647255]
 [0.17277484 0.494739  ]]

An array with values from 0 to 30 with a step of 5: [ 0  5 10 15 20 25]


In [1]:
import numpy as np
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]
              ])
temp=arr[:2,::2]
print(temp)


[[ 1  3  5]
 [ 6  8 10]]


In [4]:
a=np.array([1,2,3,4,5])

print("Addding 1 in each element of the array:",a+1)
print("Subtracting 1 from each element of the array:",a-1)
print("Multiplying each element of the array by 2:",a*2)
print("Squaring each element of the array:",a**2)

a*=2
print("After multiplying each element of the array by 2:",a)

b=np.array([[1,2,3,4,5],
           [6,7,8,9,10],
           [11,12,13,14,15]
           ])

print("Oroginal Array:\n",b)
print("Transpose of the array:\n",b.T)




Addding 1 in each element of the array: [2 3 4 5 6]
Subtracting 1 from each element of the array: [0 1 2 3 4]
Multiplying each element of the array by 2: [ 2  4  6  8 10]
Squaring each element of the array: [ 1  4  9 16 25]
After multiplying each element of the array by 2: [ 2  4  6  8 10]
Oroginal Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Transpose of the array:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [9]:
np_array_2D=np.arange(0,6).reshape(2,3)
print("Original Array:\n",np_array_2D)

a=np.sum(np_array_2D)
print("Sum of all elements in the array:",a)
a=np.sum(np_array_2D, axis=0)
print("Sum of each column in the array:",a)

Original Array:
 [[0 1 2]
 [3 4 5]]
Sum of all elements in the array: 15
Sum of each column in the array: [3 5 7]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(0,100,200)
y=np.sin(x)
plt.plot(x,y)
plt.show()